/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package labgraficas;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.data.general.DefaultPieDataset;
/**
 *
 * @author DavidLeon
 */
public class interfaz extends javax.swing.JFrame {
List<LectorCsvArhivo> lectores = new ArrayList<>();
    /**
     * Creates new form interfaz
     */
    public interfaz() {
        initComponents();
    }
    private void CargarDatos(){
    
        String csvFile = "datos.csv";
        String line="";
        String cvsSplitBy=";";
        
         try (BufferedReader br = new BufferedReader(new FileReader(csvFile))) {
        while ((line = br.readLine()) != null) {
            String[] data = line.split(cvsSplitBy);
            LectorCsvArhivo newLector = new LectorCsvArhivo();
            newLector.setCodigo(data[1]);
            newLector.setGrupoEdad(data[3]);
            newLector.setNivelAcademico(data[7]);
            newLector.setGenero(data[9]);
            lectores.add(newLector);
        }
         }catch(IOException e){
         e.printStackTrace();
         }}
        
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        filtro1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jbotoncargar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        Generar = new javax.swing.JButton();
        Barras = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 255, 51));
        jLabel1.setText("Datos Estadisticos.");

        jLabel2.setText("-Genero");

        jLabel3.setText("-Nivel Academico");

        jLabel4.setText("-Pais");

        jLabel5.setText("Variable a explorar:");

        filtro1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filtro1ActionPerformed(evt);
            }
        });

        jLabel6.setText("Click:");

        jbotoncargar.setText("Cargar Datos");
        jbotoncargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbotoncargarActionPerformed(evt);
            }
        });

        jLabel7.setText("Seleccionar grafico:");

        Generar.setText("Grafico de Torta");
        Generar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenerarActionPerformed(evt);
            }
        });

        Barras.setText("Grafico de Barras");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 198, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jLabel6)
                        .addGap(41, 41, 41)
                        .addComponent(jbotoncargar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(100, 100, 100)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(filtro1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Barras)
                            .addComponent(Generar)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(jLabel1)))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(filtro1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6))
                    .addComponent(jbotoncargar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Generar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Barras))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void filtro1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filtro1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_filtro1ActionPerformed

    private void jbotoncargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbotoncargarActionPerformed
CargarDatos();        // TODO add your handling code here:
    }//GEN-LAST:event_jbotoncargarActionPerformed

    private void GenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenerarActionPerformed
       String filtro = filtro1.getText();
       int n1=0,n2=0,n3=0,n4=0,n5=0,n6,n7,n8,n9,n10,n11,n12,n13,n14,n15;
       int contDEU=0,contBRA=0,contCHN=0,contUSA=0,contFRA=0,contIND=0,contITA=0,contJPN=0,contGBR=0,contARG=0;
       int contadorPregrado=0,contadorPostgrado=0,contadorPrimaria=0,contadorBachillerato = 0, contadorNoIndica = 0,contfem=0,contmas=0;
       int contAdult=0;
       int contAdultJ=0;
       try{
       for(LectorCsvArhivo lector : lectores){
        if (filtro.equalsIgnoreCase("nivel academico")){
        switch (lector.getNivelAcademico().toUpperCase()){
            case "PREGRADO":
                n1=contadorPregrado++;
                break;
            case "POSTGRADO":
                   n2= contadorPostgrado++;
                    break;
                case "PRIMARIA":
                   n3= contadorPrimaria++;
                    break;
                case "BACHILLERATO":
                   n4= contadorBachillerato++;
                    break;
                case "NO INDICA":
                   n5= contadorNoIndica++;
                   break;
        }
        DefaultCategoryDataset datos=new DefaultCategoryDataset();
        datos.setValue(n1, "Nivel de estudio", "Pregrado");
        datos.setValue(n2, "Nivel de estudio", "Postgrado");
        datos.setValue(n3, "Nivel de estudio", "Primaria");
        datos.setValue(n4, "Nivel de estudio", "Bachillerato");
        datos.setValue(n5, "Nivel de estudio", "No indica");
        }
        else if(filtro.equalsIgnoreCase("genero")){
        switch(lector.getGenero().toUpperCase()){
            case "MASCULINO":
                contmas++;
           break;
           case"FEMENINO":
               contfem++;
               break;
        }
        }
        else if(filtro.equalsIgnoreCase("pais")){
        switch (lector.getCodigo().toUpperCase()){
            case"DEU":
                contDEU++;
                break;
            case"BRA":
                contBRA++;
                break;
             case"CHN":
                 contCHN++;
                 break;
             case"USA":
                 contUSA++;
                 break;
            case"FRA":
                contFRA++;
                break;
            case"IND":
                contIND++;
                break;
            case"ITA":
                contITA++;
                break;
            case"JPN":
                contJPN++;
                break;
            case"GBR":
                contGBR++;
                break;
            case"ARG":
                contARG++;
                break;
        }
        }
         else if (filtro.equalsIgnoreCase("Grupo Edad")){
        switch (lector.getGrupoEdad().toUpperCase()){
            case "ADULTO":
                    contAdult++;
                    break;
                case "ADULTO JOVEN":
                    contAdultJ++;
                    break;
        
        }
        
        }
       }
       DefaultPieDataset datos=new DefaultPieDataset();
if (filtro.equalsIgnoreCase("nivel academico")) {
    datos.setValue("Pregrado", contadorPregrado);
    datos.setValue("Postgrado", contadorPostgrado);
    datos.setValue("Primaria", contadorPrimaria);
    datos.setValue("Bachillerato", contadorBachillerato);
    datos.setValue("No indica", contadorNoIndica);
    JFreeChart grafico_circular =ChartFactory.createPieChart(
        "Nivel de estudio 10 Potencias Mundiales",
        datos,
        true,
        true,
        false
        );
    ChartPanel panel = new ChartPanel(grafico_circular);
       panel.setMouseWheelEnabled(true);
       panel.setPreferredSize(new Dimension(300,300));
        
       jPanel1.setLayout(new BorderLayout());
       jPanel1.add(panel,BorderLayout.NORTH);
       pack();
       repaint();
}else if (filtro.equalsIgnoreCase("Genero")) {
    datos.setValue("Masculino", contmas);
    datos.setValue("Femenino", contfem);
    JFreeChart grafico_circular =ChartFactory.createPieChart(
        "Identidad de Genero de Potencias Mundiales",
        datos,
        true,
        true,
        false
        );
        ChartPanel panel = new ChartPanel(grafico_circular);
       panel.setMouseWheelEnabled(true);
       panel.setPreferredSize(new Dimension(300,300));
       
       jPanel1.setLayout(new BorderLayout());
       jPanel1.add(panel,BorderLayout.NORTH);
       pack();
       repaint();
}else if (filtro.equalsIgnoreCase("pais")) {
    datos.setValue("DEU", contDEU);
    datos.setValue("BRA", contBRA);
    datos.setValue("CHN", contCHN);
    datos.setValue("USA", contUSA);
    datos.setValue("FRA", contFRA);
    datos.setValue("IND", contIND);
    datos.setValue("ITA", contITA);
    datos.setValue("JPN", contJPN);
    datos.setValue("GBR", contGBR);
    datos.setValue("ARG", contARG);
    JFreeChart grafico_circular =ChartFactory.createPieChart(
        "Potencias Mundiales ",
        datos,
        true,
        true,
        false
        );
       ChartPanel panel = new ChartPanel(grafico_circular);
       panel.setMouseWheelEnabled(true);
       panel.setPreferredSize(new Dimension(300,300));
       
       jPanel1.setLayout(new BorderLayout());
       jPanel1.add(panel,BorderLayout.NORTH);
       pack();
       repaint();
}else if (filtro.equalsIgnoreCase("Grupo Edad")) {
    datos.setValue("Adulto", contAdult);
    datos.setValue("Adulto joven", contAdultJ);
    JFreeChart grafico_circular =ChartFactory.createPieChart(
        "Rango de edad POTENCIAS MUNDIALES",
        datos,
        true,
        true,
        false
        );
       ChartPanel panel = new ChartPanel(grafico_circular);
       panel.setMouseWheelEnabled(true);
       panel.setPreferredSize(new Dimension(300,300));
       
       jPanel1.setLayout(new BorderLayout());
       jPanel1.add(panel,BorderLayout.NORTH);
       pack();
       repaint();
}

//MSTR
if (filtro.equalsIgnoreCase("nivel academico")) {
        System.out.println("Pregrado: " + contadorPregrado);
        System.out.println("Postgrado: " + contadorPostgrado);
        System.out.println("Primaria: " + contadorPrimaria);
        System.out.println("Bachillerato: " + contadorBachillerato);
        System.out.println("No indica: " + contadorNoIndica);
        
             
    }
    if (filtro.equalsIgnoreCase("genero")) {
     System.out.println("masculino: " + contmas);
     System.out.println("femenino: " + contfem);
    }
    
     if (filtro.equalsIgnoreCase("pais")) {
     System.out.println("DEU: " + contDEU);
     System.out.println("BRA: " + contBRA);
     System.out.println("CHN: " + contCHN);
     System.out.println("USA: " + contUSA);
     System.out.println("FRA: " + contFRA);
     System.out.println("IND: " + contIND);
     System.out.println("ITA: " + contITA);
     System.out.println("JPN: " + contJPN);
     System.out.println("GBR: " + contGBR);
     System.out.println("ARG: " + contARG);
     }
    
     if (filtro.equalsIgnoreCase("Grupo Edad")) {
     System.out.println("Adulto: " + contAdult);
     System.out.println("Adulto joven: " + contAdultJ);
    } 
     
     
     
     
     
     
     
     
} catch (Exception e) {
    e.printStackTrace();
}
    
    }//GEN-LAST:event_GenerarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Barras;
    private javax.swing.JButton Generar;
    private javax.swing.JTextField filtro1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbotoncargar;
    // End of variables declaration//GEN-END:variables
}
